CREATE DATABASE IF NOT EXISTS hp_quiz CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hp_quiz;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tg_id BIGINT UNSIGNED NOT NULL UNIQUE,
  username VARCHAR(64) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  step VARCHAR(32) NOT NULL,
  current_q TINYINT UNSIGNED NOT NULL DEFAULT 0,
  scores_json JSON NULL,
  faculty VARCHAR(16) NULL,
  started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMP NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);